const String coreTablesSQL = '''

-- ═══════════════════════════════════════════════════════════════════════════════
-- Culture Collection Manager — Full Schema
-- Convention: every column prefixed with its table name
-- e.g. samples → sample_*   strains → strain_*   users → user_*
-- ═══════════════════════════════════════════════════════════════════════════════

-- ── 1. app_meta ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS app_meta (
    meta_initialized   BOOLEAN   DEFAULT false,
    meta_version       TEXT      DEFAULT '1.0'
);

-- ── 2. users ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username      TEXT      NOT NULL UNIQUE,
    user_email         TEXT,
    user_full_name     TEXT,
    user_role          TEXT      NOT NULL,   -- admin | researcher | technician | viewer
    user_status        TEXT      DEFAULT 'pending', -- pending | active | inactive
    user_phone         TEXT,
    user_orcid         TEXT,                 -- ORCID researcher identifier
    user_institution   TEXT,
    user_notes         TEXT,
    user_created_at    TIMESTAMP DEFAULT NOW(),
    user_last_login    TIMESTAMP
);

-- ── 3. storage_locations ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS storage_locations (
    location_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name        TEXT    NOT NULL,
    location_type        TEXT,              -- fridge | freezer | incubator | shelf | cabinet | room
    location_room        TEXT,              -- physical room in the building
    location_temperature TEXT,             -- e.g. "4°C", "-80°C", "25°C"
    location_capacity    INT,              -- max number of items
    location_qrcode      TEXT,
    location_notes       TEXT,
    location_created_at  TIMESTAMP DEFAULT NOW()
);

-- ── 4. samples ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS samples (
    sample_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identifiers
    sample_number            INT      UNIQUE,
    sample_rebeca            TEXT     UNIQUE,   -- REBECA collection code
    sample_ccpi              TEXT     UNIQUE,   -- CCPI collection code
    sample_permit            TEXT,             -- collection permit number (e.g. ICNF)
    sample_other_code        TEXT,

    -- Collection event
    sample_date              DATE,
    sample_collector         TEXT,
    sample_responsible       TEXT,

    -- Geography
    sample_country           TEXT,
    sample_archipelago       TEXT,
    sample_island            TEXT,
    sample_region            TEXT,
    sample_municipality      TEXT,
    sample_parish            TEXT,
    sample_local             TEXT,
    sample_gps               TEXT,
    sample_latitude          NUMERIC,
    sample_longitude         NUMERIC,
    sample_altitude_m        NUMERIC,

    -- Habitat
    sample_habitat_type      TEXT,
    sample_habitat_1         TEXT,
    sample_habitat_2         TEXT,
    sample_habitat_3         TEXT,
    sample_substrate         TEXT,
    sample_method            TEXT,

    -- Physical-chemical parameters
    sample_temperature       NUMERIC,         -- °C
    sample_ph                NUMERIC,
    sample_conductivity      NUMERIC,         -- µS/cm
    sample_oxygen            NUMERIC,         -- mg/L
    sample_salinity          NUMERIC,         -- ppt / PSU
    sample_radiation         NUMERIC,         -- µmol photons m⁻² s⁻¹
    sample_turbidity         NUMERIC,         -- NTU
    sample_depth_m           NUMERIC,

    -- Biological context
    sample_bloom             TEXT,
    sample_associated_organisms TEXT,

    -- Logistics
    sample_photos            TEXT,
    sample_preservation      TEXT,
    sample_transport_time_h  NUMERIC,

    -- Admin
    sample_project           TEXT,
    sample_observations      TEXT,
    sample_created_at        TIMESTAMP DEFAULT NOW()
);

-- ── 5. strains ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strains (
    strain_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strain_sample_id             BIGINT REFERENCES samples(sample_id) ON DELETE SET NULL,

    -- Identity & status
    strain_code                  TEXT UNIQUE,
    strain_status                TEXT,         -- alive | dead | lost | cryopreserved | transferred
    strain_origin                TEXT,
    strain_situation             TEXT,         -- in culture | deposited | lost | quarantine
    strain_toxins                TEXT,
    strain_public                TEXT,         -- yes | no | restricted
    strain_private_collection    TEXT,
    strain_type_strain           TEXT,         -- yes | no
    strain_last_checked          DATE,
    strain_biosafety_level       TEXT,         -- BSL-1 | BSL-2 | BSL-3
    strain_access_conditions     TEXT,
    strain_other_codes           TEXT,

    -- Taxonomy
    strain_empire                TEXT,         -- Bacteria | Archaea | Eukaryota | Virus
    strain_kingdom               TEXT,
    strain_phylum                TEXT,
    strain_class                 TEXT,
    strain_order                 TEXT,
    strain_family                TEXT,
    strain_genus                 TEXT,
    strain_species               TEXT,
    strain_subspecies            TEXT,
    strain_variety               TEXT,
    strain_scientific_name       TEXT,
    strain_authority             TEXT,
    strain_other_names           TEXT,
    strain_taxonomist            TEXT,
    strain_identification_method TEXT,         -- morphology | 16S | 18S | ITS | genome | combined
    strain_identification_date   DATE,

    -- Morphology
    strain_morphology            TEXT,         -- unicellular | filamentous | colonial | coccoid
    strain_cell_shape            TEXT,
    strain_cell_size_um          TEXT,
    strain_motility              TEXT,         -- motile | non-motile | gliding
    strain_pigments              TEXT,
    strain_colonial_morphology   TEXT,

    -- Photos
    strain_photo                 TEXT,
    strain_public_photo          TEXT,
    strain_microscopy_photo      TEXT,

    -- Herbarium deposition
    strain_herbarium_code        TEXT,
    strain_herbarium_name        TEXT,         -- e.g. Ruy Telles Palhinha Herbarium
    strain_herbarium_status      TEXT,         -- present | missing | on loan
    strain_herbarium_date        DATE,
    strain_herbarium_method      TEXT,
    strain_herbarium_notes       TEXT,

    -- Culture maintenance
    strain_last_transfer         DATE,
    strain_periodicity           INT,          -- transfer interval in days
    strain_next_transfer         DATE,
    strain_medium                TEXT,         -- BG11 | f/2 | LB | …
    strain_medium_salinity       TEXT,         -- freshwater | marine | brackish
    strain_light_cycle           TEXT,         -- e.g. "12:12 L:D"
    strain_light_intensity_umol  NUMERIC,      -- µmol photons m⁻² s⁻¹
    strain_temperature_c         NUMERIC,      -- incubation °C
    strain_co2_pct               NUMERIC,
    strain_aeration              TEXT,         -- still | shaken | bubbled | perfused
    strain_culture_vessel        TEXT,         -- flask | plate | tube | bioreactor
    strain_room                  TEXT,
    strain_location_id           BIGINT REFERENCES storage_locations(location_id),
    strain_position_in_location  TEXT,

    -- Cryopreservation
    strain_cryo_date             DATE,
    strain_cryo_method           TEXT,         -- glycerol | DMSO | liquid nitrogen | lyophilisation
    strain_cryo_location         TEXT,
    strain_cryo_vials            INT,
    strain_cryo_responsible      TEXT,

    -- Isolation
    strain_isolation_responsible TEXT,
    strain_isolation_date        DATE,
    strain_isolation_method      TEXT,         -- single cell | serial dilution | plating
    strain_deposit_date          DATE,

    -- Molecular — prokaryotes
    strain_seq_16s_bp            INT,
    strain_its                   TEXT,
    strain_its_bands             TEXT,
    strain_cloned_gel            TEXT,
    strain_genbank_16s_its       TEXT,
    strain_genbank_status        TEXT,         -- submitted | published | pending | none
    strain_genome_pct            NUMERIC,
    strain_genome_cont           INT,
    strain_genome_16s            TEXT,
    strain_gca_accession         TEXT,

    -- Molecular — eukaryotes
    strain_seq_18s_bp            INT,
    strain_genbank_18s           TEXT,
    strain_its2_bp               INT,
    strain_genbank_its2          TEXT,
    strain_rbcl_bp               INT,
    strain_genbank_rbcl          TEXT,
    strain_tufa_bp               INT,          -- tufA (green algae)
    strain_genbank_tufa          TEXT,
    strain_cox1_bp               INT,          -- COX1 (some protists / algae)
    strain_genbank_cox1          TEXT,

    -- Bioactivity & applications
    strain_bioactivity           TEXT,
    strain_metabolites           TEXT,
    strain_industrial_use        TEXT,
    strain_growth_rate           TEXT,

    -- References
    strain_publications          TEXT,
    strain_external_links        TEXT,
    strain_notes                 TEXT,
    strain_qrcode                TEXT,

    strain_created_at            TIMESTAMP DEFAULT NOW(),
    strain_updated_at            TIMESTAMP DEFAULT NOW()
);

-- ── 6. requested_strains ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS requested_strains (
    requested_strain_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What is being requested
    requested_strain_strain_id              BIGINT REFERENCES strains(strain_id),
    requested_strain_strain_code            TEXT,    -- snapshot for external / pre-isolation requests
    requested_strain_quantity               INT,
    requested_strain_format                 TEXT,    -- agar | liquid | cryovial | DNA

    -- Requester
    requested_strain_requester_name         TEXT NOT NULL,
    requested_strain_requester_email        TEXT,
    requested_strain_requester_institution  TEXT,
    requested_strain_requester_country      TEXT,
    requested_strain_requester_group        TEXT,

    -- Purpose
    requested_strain_purpose                TEXT,    -- research | teaching | commercial
    requested_strain_project_title          TEXT,
    requested_strain_funding_source         TEXT,
    requested_strain_publication            TEXT,

    -- Legal / compliance
    requested_strain_mta_required           BOOLEAN,
    requested_strain_mta_sent_date          DATE,
    requested_strain_mta_signed_date        DATE,
    requested_strain_nagoya_status          TEXT,    -- compliant | restricted | not_applicable
    requested_strain_export_permit          TEXT,

    -- Internal workflow
    requested_strain_status                 TEXT DEFAULT 'received',
    -- received | under_review | approved | rejected | in_preparation | shipped | completed | cancelled
    requested_strain_received_date          DATE,
    requested_strain_reviewed_by            BIGINT REFERENCES users(user_id),
    requested_strain_approved_by            BIGINT REFERENCES users(user_id),
    requested_strain_prepared_by            BIGINT REFERENCES users(user_id),

    -- Shipment
    requested_strain_shipment_date          DATE,
    requested_strain_shipping_method        TEXT,    -- courier | pickup | dry ice
    requested_strain_tracking_number        TEXT,
    requested_strain_shipping_cost          NUMERIC,
    requested_strain_viability_check        BOOLEAN,

    -- Storage / batch
    requested_strain_batch_id               TEXT,
    requested_strain_location_id            BIGINT REFERENCES storage_locations(location_id),

    -- Communication
    requested_strain_last_contact_date      DATE,

    -- Metadata
    requested_strain_notes                  TEXT,
    requested_strain_created_at             TIMESTAMP DEFAULT NOW(),
    requested_strain_updated_at             TIMESTAMP
);

-- ── 7. protocols ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS protocols (
    protocol_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_title               TEXT      NOT NULL,
    protocol_code                TEXT      UNIQUE,   -- e.g. "SOP-001"
    protocol_type                TEXT,              -- SOP | method | recipe | safety | maintenance
    protocol_category            TEXT,              -- isolation | culture | molecular | fish | imaging | …
    protocol_version             TEXT      DEFAULT '1.0',
    protocol_status              TEXT      DEFAULT 'draft', -- draft | active | retired
    protocol_description         TEXT,
    protocol_materials           TEXT,
    protocol_steps               TEXT,              -- Markdown
    protocol_safety_notes        TEXT,
    protocol_created_by          BIGINT    REFERENCES users(user_id),
    protocol_reviewed_by         BIGINT    REFERENCES users(user_id),
    protocol_approved_by         BIGINT    REFERENCES users(user_id),
    protocol_created_at          TIMESTAMP DEFAULT NOW(),
    protocol_updated_at          TIMESTAMP DEFAULT NOW(),
    protocol_review_date         DATE,
    protocol_next_review_date    DATE,
    protocol_file_link           TEXT,
    protocol_notes               TEXT
);

-- ── 8. reagents ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reagents (
    reagent_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reagent_name             TEXT    NOT NULL,
    reagent_brand            TEXT,
    reagent_reference        TEXT,
    reagent_cas_number       TEXT,
    reagent_type             TEXT,             -- chemical | biological | kit | media | gas | consumable
    reagent_unit             TEXT,             -- mL | g | L | mg | units
    reagent_quantity         NUMERIC,
    reagent_quantity_min     NUMERIC,          -- reorder threshold
    reagent_concentration    TEXT,
    reagent_purity           TEXT,
    reagent_solvent          TEXT,
    reagent_storage_temp     TEXT,             -- RT | 4°C | -20°C | -80°C
    reagent_location_id      BIGINT REFERENCES storage_locations(location_id),
    reagent_position         TEXT,
    reagent_lot_number       TEXT,
    reagent_expiry_date      DATE,
    reagent_received_date    DATE,
    reagent_opened_date      DATE,
    reagent_supplier         TEXT,
    reagent_supplier_contact TEXT,
    reagent_price_eur        NUMERIC,
    reagent_hazard           TEXT,             -- GHS codes e.g. "H225 H302"
    reagent_sds_link         TEXT,
    reagent_project          TEXT,
    reagent_responsible      TEXT,
    reagent_notes            TEXT,
    reagent_created_at       TIMESTAMP DEFAULT NOW()
);

-- ── 9. equipment ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS equipment (
    equipment_id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name                      TEXT    NOT NULL,
    equipment_type                      TEXT,
    equipment_brand                     TEXT,
    equipment_model                     TEXT,
    equipment_serial_number             TEXT,
    equipment_patrimony_number          TEXT,
    equipment_location_id               BIGINT REFERENCES storage_locations(location_id),
    equipment_room                      TEXT,
    equipment_status                    TEXT,   -- operational | maintenance | broken | retired
    equipment_purchase_date             DATE,
    equipment_warranty_until            DATE,
    equipment_last_calibration          DATE,
    equipment_next_calibration          DATE,
    equipment_calibration_interval_days INT,
    equipment_last_maintenance          DATE,
    equipment_next_maintenance          DATE,
    equipment_maintenance_interval_days INT,
    equipment_responsible               TEXT,
    equipment_manual_link               TEXT,
    equipment_supplier                  TEXT,
    equipment_supplier_contact          TEXT,
    equipment_price_eur                 NUMERIC,
    equipment_notes                     TEXT,
    equipment_created_at                TIMESTAMP DEFAULT NOW()
);

-- ── 10. reservations (generic — equipment | room | incubator | microscope …) ──
CREATE TABLE IF NOT EXISTS reservations (
    reservation_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What is being reserved
    reservation_resource_type    TEXT      NOT NULL,
    -- equipment | room | incubator | microscope | flow_cytometer | autoclave | …
    reservation_resource_id      BIGINT,
    -- FK resolved in app layer: points to equipment(equipment_id),
    -- storage_locations(location_id), etc. depending on resource_type
    reservation_resource_name    TEXT,             -- denormalised label for display

    -- Who booked
    reservation_user_id          BIGINT    REFERENCES users(user_id),

    -- Time window
    reservation_start            TIMESTAMP NOT NULL,
    reservation_end              TIMESTAMP NOT NULL,

    -- Context
    reservation_purpose          TEXT,
    reservation_project          TEXT,
    reservation_experiment       TEXT,

    -- Status workflow
    reservation_status           TEXT      DEFAULT 'confirmed',
    -- pending | confirmed | in_use | completed | cancelled | no_show

    -- Usage tracking
    reservation_checkin_time     TIMESTAMP,
    reservation_checkout_time    TIMESTAMP,

    -- Metadata
    reservation_notes            TEXT,
    reservation_created_at       TIMESTAMP DEFAULT NOW(),
    reservation_updated_at       TIMESTAMP
);

-- ── 11. zebrafish_facility (tanks) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS zebrafish_facility (
    zebra_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zebra_tank_id                TEXT    NOT NULL UNIQUE,
    zebra_tank_type              TEXT,          -- breeding | holding | quarantine | experimental
    zebra_rack                   TEXT,
    zebra_row                    TEXT,
    zebra_column                 TEXT,
    zebra_capacity               INT,
    zebra_volume_l               NUMERIC,
    zebra_line                   TEXT,
    zebra_genotype               TEXT,
    zebra_males                  INT,
    zebra_females                INT,
    zebra_juveniles              INT,
    zebra_dob                    DATE,
    zebra_responsible            TEXT,
    zebra_status                 TEXT,          -- active | empty | quarantine | retired
    zebra_light_cycle            TEXT,
    zebra_temperature_c          NUMERIC,
    zebra_conductivity           NUMERIC,
    zebra_ph                     NUMERIC,
    zebra_last_tank_cleaning     DATE,
    zebra_cleaning_interval_days INT,
    zebra_feeding_schedule       TEXT,
    zebra_last_health_check      DATE,
    zebra_health_status          TEXT,          -- healthy | sick | treatment | observation
    zebra_treatment              TEXT,
    zebra_experiment_id          TEXT,
    zebra_ethics_approval        TEXT,
    zebra_notes                  TEXT,
    zebra_created_at             TIMESTAMP DEFAULT NOW()
);

-- ── 12. fishlines ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fishlines (
    fishline_id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Core identity
    fishline_name                    TEXT NOT NULL UNIQUE,  -- e.g. Tg(mpx:GFP)
    fishline_alias                   TEXT,
    fishline_type                    TEXT,   -- WT | transgenic | mutant | CRISPR | KO | KI
    fishline_status                  TEXT,   -- active | archived | cryopreserved | lost

    -- Genotype & zygosity
    fishline_genotype                TEXT,
    fishline_zygosity                TEXT,   -- homozygous | heterozygous | unknown
    fishline_generation              TEXT,   -- F1 | F2 | F3 | …

    -- Genetic details
    fishline_affected_gene           TEXT,
    fishline_affected_chromosome     TEXT,
    fishline_mutation_type           TEXT,   -- insertion | deletion | point mutation
    fishline_mutation_description    TEXT,
    fishline_transgene               TEXT,
    fishline_construct               TEXT,
    fishline_promoter                TEXT,
    fishline_reporter                TEXT,   -- GFP | RFP | mCherry | …
    fishline_target_tissue           TEXT,

    -- Origin & provenance
    fishline_origin_lab              TEXT,
    fishline_origin_person           TEXT,
    fishline_date_created            DATE,
    fishline_date_received           DATE,
    fishline_source                  TEXT,   -- ZIRC | EZRC | collaborator | in-house
    fishline_import_permit           TEXT,
    fishline_mta                     TEXT,

    -- Publications & identifiers
    fishline_zfin_id                 TEXT,
    fishline_pubmed                  TEXT,
    fishline_doi                     TEXT,

    -- Cryopreservation
    fishline_cryopreserved           BOOLEAN,
    fishline_cryo_location           TEXT,
    fishline_cryo_date               DATE,
    fishline_cryo_method             TEXT,

    -- Phenotype & health
    fishline_phenotype               TEXT,
    fishline_lethality               TEXT,
    fishline_health_notes            TEXT,

    -- Facility tracking
    fishline_spf_status              TEXT,   -- SPF | non-SPF | unknown
    fishline_risk_level              TEXT,

    -- Digital
    fishline_qrcode                  TEXT,
    fishline_barcode                 TEXT,

    -- Metadata
    fishline_created_at              TIMESTAMP DEFAULT NOW(),
    fishline_updated_at              TIMESTAMP,
    fishline_notes                   TEXT
);

-- ── 13. messages (Lab Chat) ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
    message_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_user_id      BIGINT    REFERENCES users(user_id) ON DELETE SET NULL,

    -- Channel / context
    message_channel      TEXT      NOT NULL DEFAULT 'general',
    -- general | strains | samples | fish | reagents | equipment | announcements
    message_context_type TEXT,     -- optional: pin message to a record type
    -- strain | sample | fishline | reagent | equipment | protocol
    message_context_id   BIGINT,   -- optional: FK resolved in app layer

    -- Content
    message_body         TEXT      NOT NULL,
    message_edited       BOOLEAN   DEFAULT false,
    message_edited_at    TIMESTAMP,

    -- Threading
    message_parent_id    BIGINT    REFERENCES messages(message_id) ON DELETE CASCADE,
    -- null = top-level, non-null = reply in thread

    -- Reactions / pinning (lightweight)
    message_pinned       BOOLEAN   DEFAULT false,
    message_pinned_by    BIGINT    REFERENCES users(user_id),

    -- Metadata
    message_created_at   TIMESTAMP DEFAULT NOW(),
    message_deleted      BOOLEAN   DEFAULT false  -- soft delete
);

-- ── 14. audit_log ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
    audit_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_table          TEXT      NOT NULL,
    audit_record_id      BIGINT,
    audit_action         TEXT      NOT NULL,  -- INSERT | UPDATE | DELETE | LOGIN | EXPORT
    audit_user_id        BIGINT    REFERENCES users(user_id),
    audit_timestamp      TIMESTAMP DEFAULT NOW(),
    audit_old_values     TEXT,               -- JSON snapshot before
    audit_new_values     TEXT,               -- JSON snapshot after
    audit_ip_address     TEXT,
    audit_notes          TEXT
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Indexes
-- ═══════════════════════════════════════════════════════════════════════════════

-- strains
CREATE INDEX IF NOT EXISTS idx_strains_sample_id       ON strains(strain_sample_id);
CREATE INDEX IF NOT EXISTS idx_strains_code            ON strains(strain_code);
CREATE INDEX IF NOT EXISTS idx_strains_genus_species   ON strains(strain_genus, strain_species);
CREATE INDEX IF NOT EXISTS idx_strains_status          ON strains(strain_status);
CREATE INDEX IF NOT EXISTS idx_strains_next_transfer   ON strains(strain_next_transfer);
CREATE INDEX IF NOT EXISTS idx_strains_empire          ON strains(strain_empire);

-- samples
CREATE INDEX IF NOT EXISTS idx_samples_number          ON samples(sample_number);
CREATE INDEX IF NOT EXISTS idx_samples_rebeca          ON samples(sample_rebeca);
CREATE INDEX IF NOT EXISTS idx_samples_ccpi            ON samples(sample_ccpi);
CREATE INDEX IF NOT EXISTS idx_samples_date            ON samples(sample_date);
CREATE INDEX IF NOT EXISTS idx_samples_country         ON samples(sample_country);

-- requested_strains
CREATE INDEX IF NOT EXISTS idx_req_strain_status       ON requested_strains(requested_strain_status);
CREATE INDEX IF NOT EXISTS idx_req_strain_strain_id    ON requested_strains(requested_strain_strain_id);

-- reagents
CREATE INDEX IF NOT EXISTS idx_reagents_expiry         ON reagents(reagent_expiry_date);
CREATE INDEX IF NOT EXISTS idx_reagents_quantity       ON reagents(reagent_quantity);

-- equipment
CREATE INDEX IF NOT EXISTS idx_equipment_next_maint    ON equipment(equipment_next_maintenance);
CREATE INDEX IF NOT EXISTS idx_equipment_status        ON equipment(equipment_status);

-- reservations
CREATE INDEX IF NOT EXISTS idx_reservations_resource   ON reservations(reservation_resource_type, reservation_resource_id);
CREATE INDEX IF NOT EXISTS idx_reservations_user       ON reservations(reservation_user_id);
CREATE INDEX IF NOT EXISTS idx_reservations_time       ON reservations(reservation_start, reservation_end);
CREATE INDEX IF NOT EXISTS idx_reservations_status     ON reservations(reservation_status);

-- zebrafish
CREATE INDEX IF NOT EXISTS idx_zebra_status            ON zebrafish_facility(zebra_status);
CREATE INDEX IF NOT EXISTS idx_zebra_tank_id           ON zebrafish_facility(zebra_tank_id);

-- fishlines
CREATE INDEX IF NOT EXISTS idx_fishline_status         ON fishlines(fishline_status);
CREATE INDEX IF NOT EXISTS idx_fishline_name           ON fishlines(fishline_name);

-- messages
CREATE INDEX IF NOT EXISTS idx_messages_channel        ON messages(message_channel);
CREATE INDEX IF NOT EXISTS idx_messages_user           ON messages(message_user_id);
CREATE INDEX IF NOT EXISTS idx_messages_created        ON messages(message_created_at);
CREATE INDEX IF NOT EXISTS idx_messages_context        ON messages(message_context_type, message_context_id);
CREATE INDEX IF NOT EXISTS idx_messages_parent         ON messages(message_parent_id);

-- protocols
CREATE INDEX IF NOT EXISTS idx_protocols_status        ON protocols(protocol_status);
CREATE INDEX IF NOT EXISTS idx_protocols_category      ON protocols(protocol_category);

-- audit
CREATE INDEX IF NOT EXISTS idx_audit_table_record      ON audit_log(audit_table, audit_record_id);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp         ON audit_log(audit_timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_user              ON audit_log(audit_user_id);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Seed
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO app_meta (meta_initialized, meta_version)
VALUES (true, '1.0')
ON CONFLICT DO NOTHING;

create or replace function get_public_tables()
returns table(table_name text)
language sql
security definer
as \$div\$  -- Escapado com \
  select table_name::text
  from information_schema.tables
  where table_schema = 'public'
    and table_type = 'BASE TABLE';
\$div\$;
''';