// core_tables_sql.dart - Complete PostgreSQL DDL for all core tables:
// users, samples, strains, fish_lines, fish_stocks, locations, machines,
// reagents, reservations, sops, messages, todo_items. Used by setup_page.

const String coreTablesSQL = '''

-- ═══════════════════════════════════════════════════════════════════════════════
-- Culture Collection Manager — Full Schema
-- Convention: every column prefixed with its table name
-- e.g. samples → sample_*   strains → strain_*   users → user_*
-- ═══════════════════════════════════════════════════════════════════════════════

-- ── Extensions ─────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS citext;

-- ── 1. app_meta ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS app_meta (
    meta_initialized   BOOLEAN   DEFAULT false,
    meta_version       TEXT      DEFAULT '1.0',
    meta_settings      JSONB     DEFAULT '{}'
);
-- Migrate existing installations: add meta_settings if not present
ALTER TABLE app_meta ADD COLUMN IF NOT EXISTS meta_settings JSONB DEFAULT '{}';

-- ── 2. users ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_auth_uid uuid UNIQUE,  -- for external auth providers (e.g. Supabase auth UID)

    user_email   CITEXT NOT NULL UNIQUE,
    user_name    TEXT,

    user_role    TEXT NOT NULL DEFAULT 'researcher'
                 CHECK (user_role IN ('superadmin', 'admin', 'technician', 'researcher', 'viewer')),

    user_status  TEXT DEFAULT 'pending'
                 CHECK (user_status IN ('pending','active','inactive')),

    user_phone   TEXT,

    user_orcid   TEXT,

    user_institution TEXT,
    user_group   TEXT,

    user_avatar_url TEXT,
    user_bio        TEXT,
    user_timezone   TEXT,
    user_language   TEXT,

    user_table_dashboard TEXT DEFAULT 'none'
        CHECK (user_table_dashboard IN ('read','write','none')),

    user_table_chat TEXT DEFAULT 'none'
        CHECK (user_table_chat IN ('read','write','none')),

    user_table_culture_collection TEXT DEFAULT 'none'
        CHECK (user_table_culture_collection IN ('read','write','none')),

    user_table_fish_facility TEXT DEFAULT 'none'
        CHECK (user_table_fish_facility IN ('read','write','none')),
    user_table_labels TEXT DEFAULT 'none'
        CHECK (user_table_labels IN ('read','write','none')),
    user_table_resources TEXT DEFAULT 'none'
        CHECK (user_table_resources IN ('read','write','none')),

    user_notifications_enabled BOOLEAN DEFAULT true,

    user_created_at TIMESTAMP DEFAULT NOW(),
    user_updated_at TIMESTAMP DEFAULT NOW(),
    user_last_login TIMESTAMP
);

-- ── 3. storage_locations ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS storage_locations (
    location_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name        TEXT    NOT NULL,
    location_type        TEXT,              -- fridge | freezer | incubator | shelf | cabinet | room
    location_room        TEXT,              -- physical room in the building
    location_temperature TEXT,             -- e.g. "4°C", "-80°C", "25°C"
    location_capacity    INT,              -- max number of items
    location_parent_id   BIGINT REFERENCES storage_locations(location_id),
    location_qrcode      TEXT,
    location_notes       TEXT,
    location_created_at  TIMESTAMP DEFAULT NOW()
);

-- ── 4. samples ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS samples (
    sample_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identifiers
    sample_code              TEXT     UNIQUE,
    sample_rebeca            TEXT,
    sample_ccpi              TEXT,
    sample_permit            TEXT,             
    sample_other_code        TEXT,

    -- Collection event
    sample_date              DATE,
    sample_collector         TEXT,
    sample_responsible       TEXT,

    -- Geography
    sample_country           TEXT,
    sample_archipelago       TEXT,
    sample_island            TEXT,
    sample_region            TEXT,
    sample_municipality      TEXT,
    sample_parish            TEXT,
    sample_local             TEXT,
    sample_gps               TEXT,
    sample_latitude          NUMERIC,
    sample_longitude         NUMERIC,
    sample_altitude_m        NUMERIC,

    -- Habitat
    sample_habitat_type      TEXT,
    sample_habitat_1         TEXT,
    sample_habitat_2         TEXT,
    sample_habitat_3         TEXT,
    sample_substrate         TEXT,
    sample_method            TEXT,

    -- Physical-chemical parameters
    sample_temperature       NUMERIC,         -- °C
    sample_ph                NUMERIC,
    sample_conductivity      NUMERIC,         -- µS/cm
    sample_oxygen            NUMERIC,         -- mg/L
    sample_salinity          NUMERIC,         -- ppt / PSU
    sample_radiation         NUMERIC,         -- µmol photons m⁻² s⁻¹
    sample_turbidity         NUMERIC,         -- NTU
    sample_depth_m           NUMERIC,

    -- Biological context
    sample_bloom             TEXT,
    sample_associated_organisms TEXT,

    -- Logistics
    sample_photos            TEXT,
    sample_preservation      TEXT,
    sample_transport_time_h  NUMERIC,

    -- Admin
    sample_project           TEXT,
    sample_observations      TEXT,
    sample_created_by        BIGINT REFERENCES users(user_id),
    sample_created_at        TIMESTAMP DEFAULT NOW(),
    sample_updated_at        TIMESTAMP DEFAULT NOW()
);

-- ── 5. strains ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strains (
    strain_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identity & status
    strain_sample_code           TEXT REFERENCES samples(sample_code),  -- optional FK to samples(sample_code) for provenance
    strain_code                  TEXT UNIQUE,
    strain_status                TEXT,         -- alive | dead | lost | cryopreserved | transferred
    strain_origin                TEXT,
    strain_situation             TEXT,         -- in culture | deposited | lost | quarantine
    strain_toxins                TEXT,
    strain_public                TEXT,         -- yes | no | restricted
    strain_private_collection    TEXT,
    strain_type_strain           TEXT,         -- yes | no
    strain_last_checked          DATE,
    strain_biosafety_level       TEXT,         -- BSL-1 | BSL-2 | BSL-3
    strain_access_conditions     TEXT,
    strain_other_codes           TEXT,

    -- Taxonomy
    strain_empire                TEXT,         -- Bacteria | Archaea | Eukaryota | Virus
    strain_kingdom               TEXT,
    strain_phylum                TEXT,
    strain_class                 TEXT,
    strain_order                 TEXT,
    strain_family                TEXT,
    strain_genus                 TEXT,
    strain_species               TEXT,
    strain_subspecies            TEXT,
    strain_variety               TEXT,
    strain_scientific_name       TEXT,
    strain_authority             TEXT,
    strain_other_names           TEXT,
    strain_taxonomist            TEXT,
    strain_identification_method TEXT,         -- morphology | 16S | 18S | ITS | genome | combined
    strain_identification_date   DATE,

    -- Morphology
    strain_morphology            TEXT,         -- unicellular | filamentous | colonial | coccoid
    strain_cell_shape            TEXT,
    strain_cell_size_um          TEXT,
    strain_motility              TEXT,         -- motile | non-motile | gliding
    strain_pigments              TEXT,
    strain_colonial_morphology   TEXT,

    -- Photos
    strain_photo                 TEXT,
    strain_public_photo          TEXT,
    strain_microscopy_photo      TEXT,

    -- Herbarium deposition
    strain_herbarium_code        TEXT,
    strain_herbarium_name        TEXT,         -- e.g. Ruy Telles Palhinha Herbarium
    strain_herbarium_status      TEXT,         -- present | missing | on loan
    strain_herbarium_date        DATE,
    strain_herbarium_method      TEXT,
    strain_herbarium_notes       TEXT,

    -- Culture maintenance
    strain_last_transfer         DATE,
    strain_periodicity           INT,          -- transfer interval in days
    strain_next_transfer         DATE,
    strain_medium                TEXT,         -- BG11 | f/2 | LB | …
    strain_medium_salinity       TEXT,         -- freshwater | marine | brackish
    strain_light_cycle           TEXT,         -- e.g. "12:12 L:D"
    strain_light_intensity_umol  NUMERIC,      -- µmol photons m⁻² s⁻¹
    strain_temperature_c         NUMERIC,      -- incubation °C
    strain_co2_pct               NUMERIC,
    strain_aeration              TEXT,         -- still | shaken | bubbled | perfused
    strain_culture_vessel        TEXT,         -- flask | plate | tube | bioreactor
    strain_room                  TEXT,
    strain_location_id           BIGINT REFERENCES storage_locations(location_id),
    strain_position_in_location  TEXT,

    -- Cryopreservation
    strain_cryo_date             DATE,
    strain_cryo_method           TEXT,         -- glycerol | DMSO | liquid nitrogen | lyophilisation
    strain_cryo_location         TEXT,
    strain_cryo_vials            INT,
    strain_cryo_responsible      TEXT,
    strain_cryo_responsible_id   BIGINT REFERENCES users(user_id),

    -- Responsible maintainer
    strain_responsible_id        BIGINT REFERENCES users(user_id),

    -- Isolation
    strain_isolation_responsible TEXT,
    strain_isolation_responsible_id BIGINT REFERENCES users(user_id),
    strain_isolation_date        DATE,
    strain_isolation_method      TEXT,         -- single cell | serial dilution | plating
    strain_deposit_date          DATE,

    -- Molecular — prokaryotes
    strain_seq_16s_bp            INT,
    strain_its                   TEXT,
    strain_its_bands             TEXT,
    strain_cloned_gel            TEXT,
    strain_genbank_16s_its       TEXT,
    strain_genbank_status        TEXT,         -- submitted | published | pending | none
    strain_genome_pct            NUMERIC,
    strain_genome_cont           INT,
    strain_genome_16s            TEXT,
    strain_gca_accession         TEXT,

    -- Molecular — eukaryotes
    strain_seq_18s_bp            INT,
    strain_genbank_18s           TEXT,
    strain_its2_bp               INT,
    strain_genbank_its2          TEXT,
    strain_rbcl_bp               INT,
    strain_genbank_rbcl          TEXT,
    strain_tufa_bp               INT,          -- tufA (green algae)
    strain_genbank_tufa          TEXT,
    strain_cox1_bp               INT,          -- COX1 (some protists / algae)
    strain_genbank_cox1          TEXT,

    -- Bioactivity & applications
    strain_bioactivity           TEXT,
    strain_metabolites           TEXT,
    strain_industrial_use        TEXT,
    strain_growth_rate           TEXT,

    -- References
    strain_publications          TEXT,
    strain_external_links        TEXT,
    strain_notes                 TEXT,
    strain_qrcode                TEXT,

    strain_created_at            TIMESTAMP DEFAULT NOW(),
    strain_updated_at            TIMESTAMP DEFAULT NOW()
);

-- ── 6. requested_strains ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS requested_strains (
    requested_strain_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What is being requested
    requested_strain_strain_id              BIGINT REFERENCES strains(strain_id),
    requested_strain_strain_code            TEXT,    -- snapshot for external / pre-isolation requests
    requested_strain_quantity               INT,
    requested_strain_format                 TEXT,    -- agar | liquid | cryovial | DNA

    -- Requester
    requested_strain_requester_name         TEXT NOT NULL,
    requested_strain_requester_email        TEXT,
    requested_strain_requester_institution  TEXT,
    requested_strain_requester_country      TEXT,
    requested_strain_requester_group        TEXT,

    -- Purpose
    requested_strain_purpose                TEXT,    -- research | teaching | commercial
    requested_strain_project_title          TEXT,
    requested_strain_funding_source         TEXT,
    requested_strain_publication            TEXT,

    -- Legal / compliance
    requested_strain_mta_required           BOOLEAN,
    requested_strain_mta_sent_date          DATE,
    requested_strain_mta_signed_date        DATE,
    requested_strain_nagoya_status          TEXT,    -- compliant | restricted | not_applicable
    requested_strain_export_permit          TEXT,

    -- Internal workflow
    requested_strain_status                 TEXT DEFAULT 'received',
    -- received | under_review | approved | rejected | in_preparation | shipped | completed | cancelled
    requested_strain_received_date          DATE,
    requested_strain_reviewed_by            BIGINT REFERENCES users(user_id),
    requested_strain_approved_by            BIGINT REFERENCES users(user_id),
    requested_strain_prepared_by            BIGINT REFERENCES users(user_id),

    -- Shipment
    requested_strain_shipment_date          DATE,
    requested_strain_shipping_method        TEXT,    -- courier | pickup | dry ice
    requested_strain_tracking_number        TEXT,
    requested_strain_shipping_cost          NUMERIC,
    requested_strain_viability_check        BOOLEAN,

    -- Storage / batch
    requested_strain_batch_id               TEXT,
    requested_strain_location_id            BIGINT REFERENCES storage_locations(location_id),

    -- Communication
    requested_strain_last_contact_date      DATE,

    -- Metadata
    requested_strain_notes                  TEXT,
    requested_strain_created_at             TIMESTAMP DEFAULT NOW(),
    requested_strain_updated_at             TIMESTAMP
);

-- ── 7. protocols ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS protocols (
    protocol_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_title               TEXT      NOT NULL,
    protocol_code                TEXT      UNIQUE,   -- e.g. "SOP-001"
    protocol_type                TEXT,              -- SOP | method | recipe | safety | maintenance
    protocol_category            TEXT,              -- isolation | culture | molecular | fish | imaging | …
    protocol_version             TEXT      DEFAULT '1.0',
    protocol_status              TEXT      DEFAULT 'draft', -- draft | active | retired
    protocol_description         TEXT,
    protocol_materials           TEXT,
    protocol_steps               TEXT,              -- Markdown
    protocol_safety_notes        TEXT,
    protocol_created_by          BIGINT    REFERENCES users(user_id),
    protocol_reviewed_by         BIGINT    REFERENCES users(user_id),
    protocol_approved_by         BIGINT    REFERENCES users(user_id),
    protocol_created_at          TIMESTAMP DEFAULT NOW(),
    protocol_updated_at          TIMESTAMP DEFAULT NOW(),
    protocol_review_date         DATE,
    protocol_next_review_date    DATE,
    protocol_location_id         BIGINT REFERENCES storage_locations(location_id),
    protocol_file_link           TEXT,
    protocol_notes               TEXT
);

-- ── 8. reagents ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reagents (
    reagent_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reagent_name             TEXT    NOT NULL,
    reagent_brand            TEXT,
    reagent_reference        TEXT,
    reagent_cas_number       TEXT,
    reagent_type             TEXT,             -- chemical | biological | kit | media | gas | consumable
    reagent_unit             TEXT,             -- mL | g | L | mg | units
    reagent_quantity         NUMERIC,
    reagent_quantity_min     NUMERIC,          -- reorder threshold
    reagent_concentration    TEXT,
    reagent_purity           TEXT,
    reagent_solvent          TEXT,
    reagent_storage_temp     TEXT,             -- RT | 4°C | -20°C | -80°C
    reagent_location_id      BIGINT REFERENCES storage_locations(location_id),
    reagent_position         TEXT,
    reagent_lot_number       TEXT,
    reagent_expiry_date      DATE,
    reagent_received_date    DATE,
    reagent_opened_date      DATE,
    reagent_supplier         TEXT,
    reagent_supplier_contact TEXT,
    reagent_price_eur        NUMERIC,
    reagent_hazard           TEXT,             -- GHS codes e.g. "H225 H302"
    reagent_sds_link         TEXT,
    reagent_project          TEXT,
    reagent_responsible      TEXT,
    reagent_responsible_id   BIGINT REFERENCES users(user_id),
    reagent_notes            TEXT,
    reagent_qrcode           TEXT,
    reagent_created_at       TIMESTAMP DEFAULT NOW(),
    reagent_updated_at       TIMESTAMP DEFAULT NOW()
);

-- ── 9. equipment ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS equipment (
    equipment_id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name                      TEXT    NOT NULL,
    equipment_type                      TEXT,
    equipment_brand                     TEXT,
    equipment_model                     TEXT,
    equipment_serial_number             TEXT,
    equipment_patrimony_number          TEXT,
    equipment_location_id               BIGINT REFERENCES storage_locations(location_id),
    equipment_room                      TEXT,
    equipment_status                    TEXT,   -- operational | maintenance | broken | retired
    equipment_purchase_date             DATE,
    equipment_warranty_until            DATE,
    equipment_last_calibration          DATE,
    equipment_next_calibration          DATE,
    equipment_calibration_interval_days INT,
    equipment_last_maintenance          DATE,
    equipment_next_maintenance          DATE,
    equipment_maintenance_interval_days INT,
    equipment_responsible               TEXT,
    equipment_responsible_id            BIGINT REFERENCES users(user_id),
    equipment_manual_link               TEXT,
    equipment_supplier                  TEXT,
    equipment_supplier_contact          TEXT,
    equipment_price_eur                 NUMERIC,
    equipment_notes                     TEXT,
    equipment_qrcode                    TEXT,
    equipment_created_at                TIMESTAMP DEFAULT NOW()
);

-- ── 10. reservations (generic — equipment | room | incubator | microscope …) ──
CREATE TABLE IF NOT EXISTS reservations (
    reservation_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What is being reserved
    reservation_resource_type    TEXT      NOT NULL,
    -- equipment | room | incubator | microscope | flow_cytometer | autoclave | …
    reservation_resource_id      BIGINT,
    -- FK resolved in app layer: points to equipment(equipment_id),
    -- storage_locations(location_id), etc. depending on resource_type
    reservation_resource_name    TEXT,             -- denormalised label for display

    -- Who booked
    reservation_user_id          BIGINT    REFERENCES users(user_id),

    -- Time window
    reservation_start            TIMESTAMP NOT NULL,
    reservation_end              TIMESTAMP NOT NULL,

    -- Context
    reservation_purpose          TEXT,
    reservation_project          TEXT,
    reservation_experiment       TEXT,

    -- Status workflow
    reservation_status           TEXT      DEFAULT 'confirmed',
    -- pending | confirmed | in_use | completed | cancelled | no_show

    -- Usage tracking
    reservation_checkin_time     TIMESTAMP,
    reservation_checkout_time    TIMESTAMP,

    -- Metadata
    reservation_notes            TEXT,
    reservation_created_at       TIMESTAMP DEFAULT NOW(),
    reservation_updated_at       TIMESTAMP
);

-- ── 11. fishlines ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fish_lines (
    fish_line_id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Core identity
    fish_line_name                    TEXT NOT NULL UNIQUE,  -- e.g. Tg(mpx:GFP)
    fish_line_alias                   TEXT,
    fish_line_type                    TEXT,   -- WT | transgenic | mutant | CRISPR | KO | KI
    fish_line_status                  TEXT,   -- active | archived | cryopreserved | lost

    -- Genotype & zygosity
    fish_line_genotype                TEXT,
    fish_line_zygosity                TEXT,   -- homozygous | heterozygous | unknown
    fish_line_generation              TEXT,   -- F1 | F2 | F3 | …

    -- Genetic details
    fish_line_affected_gene           TEXT,
    fish_line_affected_chromosome     TEXT,
    fish_line_mutation_type           TEXT,   -- insertion | deletion | point mutation
    fish_line_mutation_description    TEXT,
    fish_line_transgene               TEXT,
    fish_line_construct               TEXT,
    fish_line_promoter                TEXT,
    fish_line_reporter                TEXT,   -- GFP | RFP | mCherry | …
    fish_line_target_tissue           TEXT,

    -- Origin & provenance
    fish_line_origin_lab              TEXT,
    fish_line_origin_person           TEXT,
    fish_line_date_birth              DATE,
    fish_line_date_received           DATE,
    fish_line_source                  TEXT,   -- ZIRC | EZRC | collaborator | in-house
    fish_line_import_permit           TEXT,
    fish_line_mta                     TEXT,

    -- Publications & identifiers
    fish_line_zfin_id                 TEXT,
    fish_line_pubmed                  TEXT,
    fish_line_doi                     TEXT,

    -- Cryopreservation
    fish_line_cryopreserved           BOOLEAN,
    fish_line_cryo_location           TEXT,
    fish_line_cryo_date               DATE,
    fish_line_cryo_method             TEXT,

    -- Phenotype & health
    fish_line_phenotype               TEXT,
    fish_line_lethality               TEXT,
    fish_line_health_notes            TEXT,

    -- Facility tracking
    fish_line_spf_status              TEXT,   -- SPF | non-SPF | unknown
    fish_line_risk_level              TEXT,
    fish_line_responsible_id          BIGINT REFERENCES users(user_id),
    fish_line_tank_count              INT DEFAULT 0,  -- denormalised count for dashboards

    -- Digital
    fish_line_qrcode                  TEXT,
    fish_line_barcode                 TEXT,

    -- Metadata
    fish_line_breeders                TEXT,  -- comma-separated list of parent line names

    -- Metadata
    fish_line_created_at              TIMESTAMP DEFAULT NOW(),
    fish_line_updated_at              TIMESTAMP DEFAULT NOW(),
    fish_line_notes                   TEXT
);

-- ── 12. zebrafish_facility (tanks) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fish_stocks (
    fish_stocks_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fish_stocks_tank_id                TEXT NOT NULL UNIQUE,

    fish_stocks_tank_type              TEXT,

    fish_stocks_rack                   TEXT,
    fish_stocks_row                    TEXT,
    fish_stocks_column                 TEXT,

    fish_stocks_capacity               INT,
    fish_stocks_volume_l               NUMERIC,

    fish_stocks_line                   TEXT,
    fish_stocks_line_id                BIGINT REFERENCES fish_lines(fish_line_id),

    fish_stocks_males                  INT DEFAULT 0 CHECK (fish_stocks_males >= 0),
    fish_stocks_females                INT DEFAULT 0 CHECK (fish_stocks_females >= 0),
    fish_stocks_juveniles              INT DEFAULT 0 CHECK (fish_stocks_juveniles >= 0),

    fish_stocks_mortality              INT DEFAULT 0 CHECK (fish_stocks_mortality >= 0),

    fish_stocks_arrival_date           DATE,
    fish_stocks_origin                 TEXT CHECK (fish_stocks_origin IN ('internal','imported','vendor')),

    fish_stocks_responsible            TEXT,
    fish_stocks_responsible_id         BIGINT REFERENCES users(user_id),

    fish_stocks_status                 TEXT,

    fish_stocks_sentinel_status        TEXT CHECK (fish_stocks_sentinel_status IN ('none','sentinel','tested')),

    fish_stocks_light_cycle            TEXT,
    fish_stocks_temperature_c          NUMERIC CHECK (fish_stocks_temperature_c > 0),
    fish_stocks_conductivity           NUMERIC,
    fish_stocks_ph                     NUMERIC CHECK (fish_stocks_ph BETWEEN 0 AND 14),

    fish_stocks_last_tank_cleaning     DATE,
    fish_stocks_cleaning_interval_days INT,

    fish_stocks_food_type              TEXT,
    fish_stocks_food_source            TEXT,
    fish_stocks_food_amount            NUMERIC,
    fish_stocks_feeding_schedule       TEXT,

    fish_stocks_last_health_check      DATE,
    fish_stocks_health_status          TEXT
        CHECK (fish_stocks_health_status IN ('healthy','sick','treatment','observation')),

    fish_stocks_treatment              TEXT,

    fish_stocks_last_breeding          DATE,

    fish_stocks_cross_id               TEXT,
    fish_stocks_breeding_group         BOOLEAN DEFAULT FALSE,
    fish_stocks_last_count_date        DATE,

    fish_stocks_experiment_id          TEXT,
    fish_stocks_ethics_approval        TEXT,

    fish_stocks_notes                  TEXT,

    fish_stocks_created_at             TIMESTAMP DEFAULT NOW(),
    fish_stocks_updated_at             TIMESTAMP DEFAULT NOW()
);

-- ── 13. messages (Lab Chat) ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
    message_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_user_uid       uuid  REFERENCES users(user_auth_uid) ON DELETE SET NULL,

    -- Channel / context
    message_channel      TEXT      NOT NULL DEFAULT 'general',
    -- general | strains | samples | fish | reagents | equipment | announcements
    message_context_type TEXT,     -- optional: pin message to a record type
    -- strain | sample | fishline | reagent | equipment | protocol
    message_context_id   BIGINT,   -- optional: FK resolved in app layer

    -- Content
    message_body         TEXT      NOT NULL,
    message_edited       BOOLEAN   DEFAULT false,
    message_edited_at    TIMESTAMP,

    -- Threading
    message_parent_id    BIGINT    REFERENCES messages(message_id) ON DELETE CASCADE,
    -- null = top-level, non-null = reply in thread

    -- Reactions / pinning (lightweight)
    message_pinned       BOOLEAN   DEFAULT false,
    message_pinned_by    BIGINT    REFERENCES users(user_id),

    -- Metadata
    message_created_at   TIMESTAMP DEFAULT NOW(),
    message_updated_at   TIMESTAMP DEFAULT NOW(),
    message_deleted      BOOLEAN   DEFAULT false  -- soft delete
);

-- ── 15. facility_sops ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS facility_sops (
    sop_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identity
    sop_code             TEXT,                      -- e.g. SOP-001, PROT-003
    sop_name             TEXT NOT NULL,
    sop_version          TEXT DEFAULT '1.0',
    sop_type             TEXT DEFAULT 'sop'
                         CHECK (sop_type IN ('sop','protocol','guideline','checklist','form','training')),
    sop_category         TEXT,                      -- Biosafety | Husbandry | Breeding | Health | Welfare …

    -- Status workflow
    sop_status           TEXT DEFAULT 'draft'
                         CHECK (sop_status IN ('draft','active','under_review','archived','superseded')),

    -- Content
    sop_description      TEXT,
    sop_tags             TEXT,                      -- comma-separated tags

    -- File storage (Supabase bucket: facility-sops)
    -- PDF slot (viewable in-app)
    sop_file_path        TEXT,                      -- storage path: {sop_id}/{filename}
    sop_file_name        TEXT,                      -- original filename
    sop_file_size        BIGINT,                    -- bytes
    sop_file_mime        TEXT,                      -- e.g. application/pdf
    -- TXT slot
    sop_txt_file_path    TEXT,
    sop_txt_file_name    TEXT,
    sop_txt_file_size    BIGINT,
    -- DOC/DOCX slot
    sop_doc_file_path    TEXT,
    sop_doc_file_name    TEXT,
    sop_doc_file_size    BIGINT,

    -- Dates
    sop_effective_date   DATE,                      -- when it became active
    sop_review_date      DATE,                      -- next scheduled review
    sop_last_reviewed    DATE,                      -- last review completed

    -- People
    sop_responsible      TEXT,                      -- display name of owner
    sop_responsible_id   BIGINT REFERENCES users(user_id),
    sop_author           TEXT,                      -- original author
    sop_last_updated_by  TEXT,                      -- last editor display name

    -- Revision history
    sop_revision_notes   TEXT,                      -- notes on latest revision

    -- Context (which section this SOP belongs to)
    sop_context          TEXT DEFAULT 'fish_facility'
                         CHECK (sop_context IN ('fish_facility','culture_collection')),

    -- Metadata
    sop_created_at       TIMESTAMP DEFAULT NOW(),
    sop_updated_at       TIMESTAMP DEFAULT NOW()
);

-- ── 14. audit_log ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
    audit_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_table          TEXT      NOT NULL,
    audit_record_id      BIGINT,
    audit_action         TEXT      NOT NULL,  -- INSERT | UPDATE | DELETE | LOGIN | EXPORT
    audit_user_id        BIGINT    REFERENCES users(user_id),
    audit_timestamp      TIMESTAMP DEFAULT NOW(),
    audit_old_values     TEXT,               -- JSON snapshot before
    audit_new_values     TEXT,               -- JSON snapshot after
    audit_ip_address     TEXT,
    audit_session_id     TEXT,
    audit_notes          TEXT
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Indexes
-- ═══════════════════════════════════════════════════════════════════════════════

--users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(user_email);
CREATE INDEX IF NOT EXISTS idx_users_role  ON users(user_role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(user_status);

-- strains
CREATE INDEX IF NOT EXISTS idx_strains_sample_code     ON strains(strain_sample_code);
CREATE INDEX IF NOT EXISTS idx_strains_code            ON strains(strain_code);
CREATE INDEX IF NOT EXISTS idx_strains_genus_species   ON strains(strain_genus, strain_species);
CREATE INDEX IF NOT EXISTS idx_strains_status          ON strains(strain_status);
CREATE INDEX IF NOT EXISTS idx_strains_next_transfer   ON strains(strain_next_transfer);
CREATE INDEX IF NOT EXISTS idx_strains_empire          ON strains(strain_empire);
CREATE INDEX IF NOT EXISTS idx_strains_kingdom         ON strains(strain_kingdom);
CREATE INDEX IF NOT EXISTS idx_strains_medium          ON strains(strain_medium);
CREATE INDEX IF NOT EXISTS idx_strains_location        ON strains(strain_location_id);
CREATE INDEX IF NOT EXISTS idx_strains_last_transfer   ON strains(strain_last_transfer);
CREATE INDEX IF NOT EXISTS idx_strains_responsible     ON strains(strain_responsible_id);

-- samples
CREATE INDEX IF NOT EXISTS idx_samples_code            ON samples(sample_code);
CREATE INDEX IF NOT EXISTS idx_samples_date            ON samples(sample_date);
CREATE INDEX IF NOT EXISTS idx_samples_country         ON samples(sample_country);
CREATE INDEX IF NOT EXISTS idx_samples_collector       ON samples(sample_collector);
CREATE INDEX IF NOT EXISTS idx_samples_responsible     ON samples(sample_responsible);
CREATE INDEX IF NOT EXISTS idx_samples_island          ON samples(sample_island);
CREATE INDEX IF NOT EXISTS idx_samples_habitat         ON samples(sample_habitat_type);

-- requested_strains
CREATE INDEX IF NOT EXISTS idx_req_strain_status       ON requested_strains(requested_strain_status);
CREATE INDEX IF NOT EXISTS idx_req_strain_strain_id    ON requested_strains(requested_strain_strain_id);
CREATE INDEX IF NOT EXISTS idx_req_received_date       ON requested_strains(requested_strain_received_date);
CREATE INDEX IF NOT EXISTS idx_req_requester_email     ON requested_strains(requested_strain_requester_email);

-- reagents
CREATE INDEX IF NOT EXISTS idx_reagents_expiry         ON reagents(reagent_expiry_date);
CREATE INDEX IF NOT EXISTS idx_reagents_quantity       ON reagents(reagent_quantity);
CREATE INDEX IF NOT EXISTS idx_reagents_type           ON reagents(reagent_type);
CREATE INDEX IF NOT EXISTS idx_reagents_location       ON reagents(reagent_location_id);

-- equipment
CREATE INDEX IF NOT EXISTS idx_equipment_next_maint    ON equipment(equipment_next_maintenance);
CREATE INDEX IF NOT EXISTS idx_equipment_status        ON equipment(equipment_status);
CREATE INDEX IF NOT EXISTS idx_equipment_location      ON equipment(equipment_location_id);
CREATE INDEX IF NOT EXISTS idx_equipment_next_cal      ON equipment(equipment_next_calibration);

-- reservations
CREATE INDEX IF NOT EXISTS idx_reservations_resource   ON reservations(reservation_resource_type, reservation_resource_id);
CREATE INDEX IF NOT EXISTS idx_reservations_user       ON reservations(reservation_user_id);
CREATE INDEX IF NOT EXISTS idx_reservations_time       ON reservations(reservation_start, reservation_end);
CREATE INDEX IF NOT EXISTS idx_reservations_status     ON reservations(reservation_status);

-- fishlines
CREATE INDEX IF NOT EXISTS idx_fishline_status         ON fish_lines(fish_line_status);
CREATE INDEX IF NOT EXISTS idx_fishline_name           ON fish_lines(fish_line_name);
CREATE INDEX IF NOT EXISTS idx_fishline_type           ON fish_lines(fish_line_type);
CREATE INDEX IF NOT EXISTS idx_fishline_source         ON fish_lines(fish_line_source);
CREATE INDEX IF NOT EXISTS idx_fishline_responsible    ON fish_lines(fish_line_responsible_id);

-- zebrafish stocks
CREATE INDEX IF NOT EXISTS idx_fish_status             ON fish_stocks (fish_stocks_status);
CREATE INDEX IF NOT EXISTS idx_fish_line               ON fish_stocks (fish_stocks_line);
CREATE INDEX IF NOT EXISTS idx_fish_line_id            ON fish_stocks (fish_stocks_line_id);
CREATE INDEX IF NOT EXISTS idx_fish_responsible        ON fish_stocks (fish_stocks_responsible_id);
CREATE INDEX IF NOT EXISTS idx_fish_health_check       ON fish_stocks (fish_stocks_last_health_check);
CREATE INDEX IF NOT EXISTS idx_fish_arrival            ON fish_stocks (fish_stocks_arrival_date);

-- messages
CREATE INDEX IF NOT EXISTS idx_messages_channel        ON messages(message_channel);
CREATE INDEX IF NOT EXISTS idx_messages_user           ON messages(message_user_uid);
CREATE INDEX IF NOT EXISTS idx_messages_created        ON messages(message_created_at);
CREATE INDEX IF NOT EXISTS idx_messages_context        ON messages(message_context_type, message_context_id);
CREATE INDEX IF NOT EXISTS idx_messages_parent         ON messages(message_parent_id);

-- protocols
CREATE INDEX IF NOT EXISTS idx_protocols_status        ON protocols(protocol_status);
CREATE INDEX IF NOT EXISTS idx_protocols_category      ON protocols(protocol_category);
CREATE INDEX IF NOT EXISTS idx_protocols_type          ON protocols(protocol_type);

-- facility_sops
CREATE INDEX IF NOT EXISTS idx_sops_status             ON facility_sops(sop_status);
CREATE INDEX IF NOT EXISTS idx_sops_type               ON facility_sops(sop_type);
CREATE INDEX IF NOT EXISTS idx_sops_category           ON facility_sops(sop_category);
CREATE INDEX IF NOT EXISTS idx_sops_review_date        ON facility_sops(sop_review_date);
CREATE INDEX IF NOT EXISTS idx_sops_responsible        ON facility_sops(sop_responsible_id);
CREATE INDEX IF NOT EXISTS idx_sops_context            ON facility_sops(sop_context);
CREATE INDEX IF NOT EXISTS idx_protocols_created_by    ON protocols(protocol_created_by);

-- audit
CREATE INDEX IF NOT EXISTS idx_audit_table_record      ON audit_log(audit_table, audit_record_id);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp         ON audit_log(audit_timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_user              ON audit_log(audit_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_action            ON audit_log(audit_action);
CREATE INDEX IF NOT EXISTS idx_audit_session           ON audit_log(audit_session_id);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Row-Level Security — disable for all app tables (access controlled by app)
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE app_meta            DISABLE ROW LEVEL SECURITY;
ALTER TABLE users               DISABLE ROW LEVEL SECURITY;
ALTER TABLE strains             DISABLE ROW LEVEL SECURITY;
ALTER TABLE samples             DISABLE ROW LEVEL SECURITY;
ALTER TABLE requested_strains   DISABLE ROW LEVEL SECURITY;
ALTER TABLE storage_locations   DISABLE ROW LEVEL SECURITY;
ALTER TABLE protocols           DISABLE ROW LEVEL SECURITY;
ALTER TABLE reagents            DISABLE ROW LEVEL SECURITY;
ALTER TABLE equipment           DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservations        DISABLE ROW LEVEL SECURITY;
ALTER TABLE fish_lines          DISABLE ROW LEVEL SECURITY;
ALTER TABLE fish_stocks         DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages            DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log           DISABLE ROW LEVEL SECURITY;
ALTER TABLE facility_sops       DISABLE ROW LEVEL SECURITY;
ALTER TABLE todo_items          DISABLE ROW LEVEL SECURITY;
ALTER TABLE label_templates     DISABLE ROW LEVEL SECURITY;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Storage — facility-sops bucket + access policy
-- ═══════════════════════════════════════════════════════════════════════════════

-- Create the bucket (private — files accessed only through the app client)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'facility-sops',
    'facility-sops',
    false,
    52428800,   -- 50 MB per file
    NULL        -- all mime types allowed
)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users full CRUD on their bucket objects
CREATE POLICY IF NOT EXISTS "facility_sops_authenticated_all"
  ON storage.objects FOR ALL
  TO authenticated
  USING  (bucket_id = 'facility-sops')
  WITH CHECK (bucket_id = 'facility-sops');

-- ═══════════════════════════════════════════════════════════════════════════════
-- Resources: add columns for hierarchy and QR codes
-- ═══════════════════════════════════════════════════════════════════════════════
ALTER TABLE storage_locations ADD COLUMN IF NOT EXISTS location_parent_id BIGINT REFERENCES storage_locations(location_id);
ALTER TABLE reagents          ADD COLUMN IF NOT EXISTS reagent_qrcode TEXT;
ALTER TABLE equipment         ADD COLUMN IF NOT EXISTS equipment_qrcode TEXT;
ALTER TABLE facility_sops     ADD COLUMN IF NOT EXISTS sop_context       TEXT DEFAULT 'fish_facility' CHECK (sop_context IN ('fish_facility','culture_collection'));
ALTER TABLE facility_sops     ADD COLUMN IF NOT EXISTS sop_txt_file_path TEXT;
ALTER TABLE facility_sops     ADD COLUMN IF NOT EXISTS sop_txt_file_name TEXT;
ALTER TABLE facility_sops     ADD COLUMN IF NOT EXISTS sop_txt_file_size BIGINT;
ALTER TABLE facility_sops     ADD COLUMN IF NOT EXISTS sop_doc_file_path TEXT;
ALTER TABLE facility_sops     ADD COLUMN IF NOT EXISTS sop_doc_file_name TEXT;
ALTER TABLE facility_sops     ADD COLUMN IF NOT EXISTS sop_doc_file_size BIGINT;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Shared To-Do list (dashboard widget)
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS todo_items (
    todo_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_title        TEXT         NOT NULL,
    todo_description  TEXT,
    todo_due_date     DATE,
    todo_is_completed BOOLEAN      NOT NULL DEFAULT false,
    todo_created_by   BIGINT       REFERENCES users(user_id) ON DELETE SET NULL,
    todo_created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    todo_updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Label Templates (Printing module)
-- fields stored as JSONB: [{id, type, content, x, y, w, h, fontSize,
--                           fontWeight, textAlign, color, isPlaceholder}]
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS label_templates (
    tpl_id          TEXT        PRIMARY KEY,
    tpl_name        TEXT        NOT NULL,
    tpl_category    TEXT        NOT NULL DEFAULT 'General'
                    CHECK (tpl_category IN ('Strains','Reagents','Equipment','Samples','Stocks','General')),
    tpl_label_w     FLOAT       NOT NULL DEFAULT 62,
    tpl_label_h     FLOAT       NOT NULL DEFAULT 30,
    tpl_paper_size  TEXT        NOT NULL DEFAULT '62x30',
    tpl_dpi         INT         NOT NULL DEFAULT 300,
    tpl_auto_cut    BOOLEAN     NOT NULL DEFAULT true,
    tpl_half_cut    BOOLEAN     NOT NULL DEFAULT false,
    tpl_rotate      BOOLEAN     NOT NULL DEFAULT false,
    tpl_copies      INT         NOT NULL DEFAULT 1,
    tpl_fields      JSONB       NOT NULL DEFAULT '[]',
    tpl_created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tpl_updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Seed
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO app_meta (meta_initialized, meta_version)
VALUES (true, '1.0')
ON CONFLICT DO NOTHING;
''';